#!/bin/bash 
set -x

yum install openssl openssl-devel pam-devel numactl numactl-devel hwloc hwloc-devel lua lua-devel readline-devel rrdtool-devel ncurses-devel man2html libibmad libibumad -y

cd /software
wget https://download.schedmd.com/slurm/slurm-18.08.3.tar.bz2

# install rpm-build
yum install 
