#!/bash/bin 
set -x 

sudo yum install epel-release
sudo yum install munge munge-libs munge-devel -y

yum install rng-tools -y
rngd -r /dev/urandom

/usr/sbin/create-munge-key -r 

dd if=/dev/urandom bs=1 count=1024 > /etc/munge/munge.key
chown munge: /etc/munge/munge.key
chmod 400 /etc/munge/munge.key

scp /etc/munge/munge.key 
